permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Kiveen
  email: zcwsmile@gmail.com
  link: http://zcwsmile.github.io
  github: http://github.com/zcwsmile
  weibo: http://weibo.com
  stackoverflow: http://stackoverflow.com

# 站点信息
title: Kiveen的博客
description: Kiveen的博客
url: http://zcwsmile.github.io
#rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /images_zc/upload/gavatar/gavatar.png
favicon: /images_zc/upload/gavatar/favicon.ico
# weixin:  /images_zc/upload/weixin/weixin.png

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh